server:
  port: 0

spring:
  application:
    name: eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://${EUREKA_HOST}:8761/eureka
